name=MNRGBLEDBaseLib
version=1.1.1
author=Mark Naylor <mark_naylor@hotmail.com>
maintainer=Mark Naylor <mark_naylor@hotmail.com>
sentence= Base library to control RGB LED
paragraph=
category=Other
architectures=samd, avr
includes=MNRGBLEDBaseLib.h
url=https://github.com/marknaylor/MNRGBLEDBaseLib